name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Enable Corepack
        run: corepack enable
          
      - name: Install dependencies with Yarn
        run: |
          yarn install
          
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Android APK
        run: |
          npx drizzle-kit generate
          npx expo prebuild --platform android
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
